
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[240] =
    {   0,
        0,    0,    0,    0,    0,    0,   79,   77,   74,   75,
       76,   52,   77,   63,   64,   37,   35,   67,   66,   40,
       40,   69,   65,   34,   68,   34,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   70,   71,   77,   58,   55,   55,
       55,   53,   57,   61,   61,   62,   59,    0,    0,    0,
       73,   43,   43,    0,    0,    0,    0,   40,   72,   34,
       51,   51,   51,    0,   51,   51,   51,   51,   51,   51,
       51,   25,   51,   51,   51,   51,   51,   21,   39,   51,
       51,   51,   51,   51,    7,   36,   51,   51,   51,   51,

       51,   29,   51,   51,   51,   51,   51,   51,    0,   56,
       55,   54,   55,   60,    0,   48,    0,    0,    0,   43,
       43,   41,    0,   44,   44,    0,   42,   37,   51,   51,
       51,   51,   50,   51,   51,   51,   37,   51,   51,   20,
       51,   28,   51,   51,   51,   51,   37,   18,   38,   51,
       51,   51,   51,    6,   51,   51,   51,    9,   51,   51,
       51,   49,    0,   43,   43,    0,   41,   44,   46,   42,
       42,   51,   51,   51,   26,   15,   51,   51,   23,   51,
       51,   51,   51,   51,    5,   51,   51,   51,   32,   13,
       51,   22,   47,    3,   51,   31,   51,   43,   45,    4,

       19,   51,    2,   51,   47,   51,   51,   51,   51,   51,
       51,   51,   51,   24,   33,   45,   51,   30,   51,   51,
       51,   17,   51,   51,   51,    8,   14,   16,   51,   12,
       51,   51,    1,   10,   51,   51,   27,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    6,    6,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   35,   36,   37,   38,   39,
       34,   40,   41,   42,   43,   44,   45,   46,   47,   34,
       48,   49,   50,    6,   51,    6,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   34,   34,   61,   62,   63,
       64,   65,   34,   66,   67,   68,   69,   70,   71,   46,
       72,   34,   73,    6,   74,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    3,    2,    2,
        2,    2,    2,    2,    4,    2,    5,    6,    6,    2,
        2,    2,    2,    2,    7,    8,    7,    7,    7,    8,
        9,    9,    9,    9,    9,    9,   10,    9,    9,   10,
        9,   10,    9,   10,    9,    9,    9,    2,    2,    2,
       11,    7,    8,    7,    7,    7,    8,    9,    9,    9,
        9,    9,   10,    9,    9,   10,    9,   10,    9,   10,
        9,    9,    2,    2
    } ;

static const flex_int16_t yy_base[250] =
    {   0,
        0,    0,   72,   74,   77,   79,  649,  733,  733,  733,
      733,  733,  149,  733,  733,  733,  733,  733,   68,   69,
       73,  624,  733,   70,  733,  622,   67,   68,  150,   76,
      152,  142,  592,   80,  175,  128,  178,  188,  144,   60,
       83,  200,   95,  217,  733,  733,    0,  733,  733,  733,
      639,  733,   96,  733,  733,  138,  733,  632,  631,  630,
      733,  244,  252,  131,  614,  268,  616,  273,  733,  733,
      579,  193,  201,  572,  202,  246,  265,  267,  273,  238,
      173,  264,  145,  266,  185,  272,  276,  549,  277,  289,
      263,  306,  291,  295,  548,  545,  309,  305,  322,  302,

      321,  543,  315,  316,  314,  331,  336,  338,  540,  733,
      733,  733,  585,  733,  583,  733,  569,  375,  383,  388,
      391,  159,  394,  733,  397,    0,   86,  493,  334,  370,
      384,  397,  491,  367,  387,  383,  490,  391,  400,  487,
      390,  388,  395,  411,  424,  418,  446,  434,  429,  414,
      437,  438,  420,  421,  439,  445,  449,  385,  426,  447,
      441,  733,  493,  733,  496,  414,  501,  503,    0,  166,
      210,  227,  466,  475,  375,  348,  481,  482,  339,  479,
      500,  485,  497,  492,  337,  505,  508,  506,  332,  328,
      507,  324,  300,  297,  510,  260,  511,  551,  127,  252,

      245,  529,  228,  443,  214,  523,  532,  546,  544,  533,
      554,  560,  559,  207,  204,  173,  556,  186,  562,  570,
      575,  168,  565,  577,  582,  117,  101,   87,  585,   84,
      586,  584,   62,   57,  550,  600,   54,   45,  733,  656,
      667,  677,  684,  689,  699,  708,  715,  719,  724
    } ;

static const flex_int16_t yy_def[250] =
    {   0,
      239,    1,  240,  240,  241,  241,  239,  239,  239,  239,
      239,  239,  242,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  239,  239,  244,  239,  239,  239,
      239,  239,  245,  239,  239,  239,  239,  239,  239,  246,
      239,  239,  239,  239,  239,  239,  247,  239,  239,  239,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  248,  249,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  239,  239,  239,  239,  239,  239,  239,  248,  249,
      249,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  239,  239,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  239,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,    0,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239
    } ;

static const flex_int16_t yy_nxt[808] =
    {   0,
        8,    9,   10,   11,    9,    8,   12,   13,   14,   15,
       16,   17,   18,   17,   19,   16,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   33,   34,   33,   35,   36,   37,   38,   39,   40,
       41,   42,   33,   43,   44,   33,   33,   45,    8,   46,
       47,   27,   28,   29,   30,   31,   32,   33,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   33,   43,
       44,   33,   48,    8,   50,   51,   50,   51,   52,   55,
       52,   55,   61,   64,   62,   63,   63,   64,   99,   68,
       68,   68,   70,   70,   65,   74,   75,   66,  112,  113,

      126,   66,  170,   72,   74,   76,   73,   74,   81,   88,
       74,  100,   74,   82,   67,   99,   89,   74,   74,  105,
       53,   65,   53,   75,   66,   56,   74,   56,   66,   72,
       74,   76,   73,   74,   74,   81,   88,   74,  100,   82,
      114,  115,   89,  216,  216,   74,  105,   62,   63,   63,
       57,   74,   57,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   92,   85,   74,   58,   58,
       58,   58,   58,  166,   77,  167,  167,   78,   74,   86,
      126,   79,  170,   98,   87,  139,   83,   80,   84,  216,
      216,   92,   74,   85,   74,   74,   58,   60,   58,   58,

       74,   77,   74,   90,   78,   86,   93,   91,   79,   98,
       87,  139,   83,   80,   84,   94,  137,   95,   74,  141,
      128,   58,   58,   74,  126,   74,  170,   96,   74,   97,
       90,  101,  130,   93,   91,   74,   74,  102,   74,  103,
      129,   94,  137,   74,   95,  141,  104,  128,  106,  107,
       74,   74,   74,   96,   74,   97,  108,   74,  101,  130,
      118,   63,   63,  102,   74,  103,  129,   74,  120,  121,
      121,  104,  119,  200,  136,  106,  107,   74,   74,  123,
      119,  123,  108,  131,  124,  125,  125,   64,   74,   68,
       68,   68,  132,  140,   78,   74,   74,  135,  200,  119,

      136,   66,   74,  146,  133,  134,  133,  119,  138,  131,
       74,  142,  143,   74,   74,   74,   74,   74,  144,  132,
      140,   78,   74,   74,  135,  145,   74,   74,   66,  146,
      133,  134,  133,  147,  138,  148,  149,  142,  143,   74,
      150,   74,  151,  154,  144,   74,  152,   74,  153,  155,
       74,  145,   74,  158,  157,   74,   74,  156,  172,   74,
      147,  148,  149,  159,   74,   74,   74,  150,  151,  154,
      161,   74,   74,  152,   74,  153,  155,  160,   74,  158,
      157,   74,   74,  156,   74,  172,   74,   74,   74,   74,
      159,  118,   63,   63,  163,  175,  163,  161,   74,  164,

      165,  165,  173,  160,  120,  120,  120,  120,  121,  121,
      124,  125,  125,  168,  168,  168,  119,   74,  174,  119,
       74,  182,  175,  177,  132,   74,  176,  178,  179,  173,
      180,  199,  181,   74,   74,   74,  133,   74,   74,  183,
       74,   74,  186,  119,  174,   74,  119,   74,  182,  177,
       74,  132,  176,  178,  184,  179,  180,  191,  181,  185,
      195,   74,  133,  187,   74,  189,  183,  188,   74,  186,
       74,   74,  190,  193,   74,  192,   74,  194,  196,   74,
      218,  184,  197,  191,   74,  185,  195,   74,   74,   74,
      187,   74,  189,   74,  188,   74,   74,   74,  190,   74,

      193,  192,  201,  202,  194,  196,  218,  205,  197,  164,
      165,  165,  198,  198,  198,  166,   74,  167,  167,  168,
      168,  168,  203,  204,  206,   74,  207,  208,  201,   74,
      202,   74,   74,  209,  205,   74,  211,   74,  214,  215,
       74,   74,   74,   74,  210,  212,  213,   74,  203,  204,
       74,  206,  207,  217,  208,   74,   74,   74,   74,  209,
       74,   74,  219,  211,  220,  214,  215,  198,  198,  198,
      210,  212,  213,   74,  221,  222,  162,  223,  237,   74,
      217,  224,   74,   74,  225,  114,  226,  112,  219,  228,
       74,  220,  227,   74,   74,   74,   74,  231,   74,   74,

       74,  221,  222,  223,   74,  237,   74,  229,  224,   74,
       74,  225,   74,  226,  230,   74,  228,  233,  227,  232,
       74,  234,   74,  236,  231,   74,  235,   74,  238,   74,
      126,  122,   74,  229,   74,   74,   74,  116,  116,  116,
      230,  110,   74,  233,   70,  232,   69,  234,  239,  236,
       74,  239,  235,  239,  239,  238,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   71,   71,
       71,   71,   71,   71,   71,  109,  109,  109,  109,  111,

      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      117,  239,  239,  239,  239,  117,  239,  117,  127,  239,
      127,  127,  127,  169,  169,  169,  169,  171,  171,  171,
      171,  171,    7,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239
    } ;

static const flex_int16_t yy_chk[808] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,    3,    5,
        4,    6,   19,   20,   19,   19,   19,   21,   40,   21,
       21,   21,   24,   24,   20,  238,   28,   20,   53,   53,

      127,   21,  127,   27,  237,   28,   27,  234,   30,   34,
       40,   41,  233,   30,   20,   40,   34,   27,   28,   43,
        3,   20,    4,   28,   20,    5,   30,    6,   21,   27,
       34,   28,   27,   41,  230,   30,   34,  228,   41,   30,
       56,   56,   34,  199,  199,   43,   43,   64,   64,   64,
        5,  227,    6,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   36,   32,  226,   13,   13,
       13,   13,   13,  122,   29,  122,  122,   29,   36,   32,
      170,   29,  170,   39,   32,   83,   31,   29,   31,  216,
      216,   36,   32,   32,   39,   83,   13,   13,   13,   13,

       29,   29,   31,   35,   29,   32,   37,   35,   29,   39,
       32,   83,   31,   29,   31,   37,   81,   38,  222,   85,
       72,   13,   13,   81,  171,   35,  171,   38,   37,   38,
       35,   42,   75,   37,   35,   85,  218,   42,   38,   42,
       73,   37,   81,   72,   38,   85,   42,   72,   44,   44,
       42,   73,   75,   38,  215,   38,   44,  214,   42,   75,
       62,   62,   62,   42,  205,   42,   73,   44,   63,   63,
       63,   42,   62,  172,   80,   44,   44,  172,  203,   66,
       63,   66,   44,   76,   66,   66,   66,   68,   80,   68,
       68,   68,   77,   84,   78,  201,   76,   79,  172,   62,

       80,   68,  200,   91,   77,   77,   78,   63,   82,   76,
      196,   86,   87,   91,   82,   77,   84,   78,   89,   77,
       84,   78,   86,   79,   79,   90,   87,   89,   68,   91,
       77,   77,   78,   92,   82,   93,   94,   86,   87,   90,
       97,   93,   98,  100,   89,   94,   99,  194,   99,  101,
      193,   90,  100,  105,  104,   98,   92,  103,  129,   97,
       92,   93,   94,  106,  105,  103,  104,   97,   98,  100,
      108,  101,   99,   99,  192,   99,  101,  107,  190,  105,
      104,  106,  189,  103,  129,  129,  107,  185,  108,  179,
      106,  118,  118,  118,  119,  134,  119,  108,  176,  119,

      119,  119,  130,  107,  120,  120,  120,  121,  121,  121,
      123,  123,  123,  125,  125,  125,  120,  134,  131,  121,
      130,  143,  134,  136,  132,  175,  135,  138,  139,  130,
      141,  166,  142,  136,  131,  158,  132,  135,  142,  144,
      141,  138,  150,  120,  131,  143,  121,  132,  143,  136,
      139,  132,  135,  138,  145,  139,  141,  153,  142,  146,
      159,  144,  132,  151,  150,  152,  144,  151,  146,  150,
      153,  154,  152,  156,  145,  155,  159,  157,  160,  149,
      204,  145,  161,  153,  148,  146,  159,  151,  152,  155,
      151,  161,  152,  204,  151,  156,  147,  160,  152,  157,

      156,  155,  173,  174,  157,  160,  204,  180,  161,  163,
      163,  163,  165,  165,  165,  167,  173,  167,  167,  168,
      168,  168,  177,  178,  181,  174,  182,  183,  173,  180,
      174,  177,  178,  184,  180,  182,  187,  140,  195,  197,
      137,  133,  184,  128,  186,  188,  191,  183,  177,  178,
      181,  181,  182,  202,  183,  186,  188,  191,  187,  184,
      195,  197,  206,  187,  207,  195,  197,  198,  198,  198,
      186,  188,  191,  206,  208,  209,  117,  210,  235,  202,
      202,  211,  207,  210,  212,  115,  213,  113,  206,  219,
      109,  207,  217,  102,  209,   96,  208,  223,   95,   88,

      235,  208,  209,  210,  211,  235,  217,  220,  211,  213,
      212,  212,  219,  213,  221,  223,  219,  225,  217,  224,
      220,  229,   74,  232,  223,  221,  231,  224,  236,   71,
       67,   65,  225,  220,  232,  229,  231,   60,   59,   58,
      221,   51,   33,  225,   26,  224,   22,  229,    7,  232,
      236,    0,  231,    0,    0,  236,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  243,  243,
      243,  243,  243,  243,  243,  244,  244,  244,  244,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      246,    0,    0,    0,    0,  246,    0,  246,  247,    0,
      247,  247,  247,  248,  248,  248,  248,  249,  249,  249,
      249,  249,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[79] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 
    1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
/* TODO List: */
/*       1) Fix -lm flag bug when able and try to change ICONST and RCONST RegEx position. */
/*       2) Define simple regex with words (Position before rules). */
/*       3) After Keywords (PROGRAM-WRITE) --> Regex () */
/*       4) Create function for str_int(char *str) -> (int) conversion for requested number base(2, 10, 16). */
/*       5) After step 4, update token_Print() to return num token of any base(2, 10, 16) to base "10". */
/*       6) If steps 4,5 are correct, create function(s) to convert same string to (real) type. */
/*       7) Create SubLexer within Rules(with RegEx) to catch Strings and Comments. */
/* DEFINES */
#line 12 "lexer.l"
/* Includes */
    #include <stdio.h>
    #include <stdlib.h>
    #include <unistd.h>
    #include <math.h>
    #include <string.h>
    #include "lexer.h"

    void token_Print(int token_val);
    int str_int(char *strptr);
    float str_float(char *strptr);

    char str_Arr[2048];
    void sp_chr_Handler(char *str_Arr);

    void error_Handler(int token_val, int id);

#line 758 "lex.yy.c"
/* Allows only one file as input. */
/* Ignores the diference between uppercase and lowercase letters. */
/* Counts the lines of the code. */
/* Sub lexers */

/* Helpful Defines. */
/* Identifier(ID) */
/*ID                (_?[a-zA-Z][a-zA-Z0-9_]*[a-zA-Z0-9])|[a-zA-Z] */
/* Integer Constants(ICONST) */
/* Real Constants(RCONST) */
/*REAL              (0)|([1-9][0-9]*)?(\.)(0*[1-9]+[0-9]*|0) */
/* RULES */
#line 771 "lex.yy.c"

#define INITIAL 0
#define SBLXR_STRING 1
#define SBLXR_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 72 "lexer.l"

#line 992 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 240 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 733 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 73 "lexer.l"
{token_Print(PROGRAM_T); return PROGRAM_T;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 74 "lexer.l"
{token_Print(CONST_T); return CONST_T;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "lexer.l"
{token_Print(TYPE_T); return TYPE_T;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "lexer.l"
{token_Print(ARRAY_T); return ARRAY_T;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "lexer.l"
{token_Print(LIST_T); return LIST_T;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "lexer.l"
{token_Print(SET_T); return SET_T;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "lexer.l"
{token_Print(OF_T); return OF_T;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "lexer.l"
{token_Print(RECORD_T); return RECORD_T;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "lexer.l"
{token_Print(VAR_T); return VAR_T;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "lexer.l"
{token_Print(FUNCTION_T); return FUNCTION_T;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "lexer.l"
{token_Print(PROCEDURE_T); return PROCEDURE_T;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "lexer.l"
{token_Print(INTEGER_T); return INTEGER_T;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "lexer.l"
{token_Print(REAL_T); return REAL_T;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "lexer.l"
{token_Print(BOOLEAN_T); return BOOLEAN_T;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "lexer.l"
{token_Print(CHAR_T); return CHAR_T;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "lexer.l"
{token_Print(FORWARD_T); return FORWARD_T;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "lexer.l"
{token_Print(LENGTH_T); return LENGTH_T;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "lexer.l"
{token_Print(NEW_T); return NEW_T;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 91 "lexer.l"
{token_Print(BEGIN_T); return BEGIN_T;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "lexer.l"
{token_Print(END_T); return END_T;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "lexer.l"
{token_Print(IF_T); return IF_T;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 94 "lexer.l"
{token_Print(THEN_T); return THEN_T;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 95 "lexer.l"
{token_Print(ELSE_T); return ELSE_T;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 96 "lexer.l"
{token_Print(WHILE_T); return WHILE_T;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 97 "lexer.l"
{token_Print(DO_T); return DO_T;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 98 "lexer.l"
{token_Print(CASE_T); return CASE_T;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 99 "lexer.l"
{token_Print(OTHERWISE_T); return OTHERWISE_T;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 100 "lexer.l"
{token_Print(FOR_T); return FOR_T;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 101 "lexer.l"
{token_Print(TO_T); return TO_T;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 102 "lexer.l"
{token_Print(DOWNTO_T); return DOWNTO_T;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "lexer.l"
{token_Print(WITH_T); return WITH_T;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 104 "lexer.l"
{token_Print(READ_T); return READ_T;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 105 "lexer.l"
{token_Print(WRITE_T); return WRITE_T;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 107 "lexer.l"
{token_Print(RELOP_T); return RELOP_T;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 108 "lexer.l"
{token_Print(ADDOP_T); return ADDOP_T;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 109 "lexer.l"
{token_Print(OROP_T); return OROP_T;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 110 "lexer.l"
{token_Print(MULDIVANDOP_T); return MULDIVANDOP_T;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 111 "lexer.l"
{token_Print(NOTOP_T); return NOTOP_T;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 112 "lexer.l"
{token_Print(INOP_T); return INOP_T;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "lexer.l"
{token_Print(ICONST_T); return ICONST_T;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "lexer.l"
{token_Print(ICONST_T); return ICONST_T;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 117 "lexer.l"
{token_Print(ICONST_T); return ICONST_T;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 119 "lexer.l"
{token_Print(RCONST_T); return RCONST_T;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "lexer.l"
{token_Print(RCONST_T); return RCONST_T;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 121 "lexer.l"
{token_Print(RCONST_T); return RCONST_T;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 122 "lexer.l"
{token_Print(RCONST_T); return RCONST_T;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "lexer.l"
{token_Print(BCONST_T); return BCONST_T;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 126 "lexer.l"
{token_Print(CCONST_T); return CCONST_T;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 127 "lexer.l"
{token_Print(CCONST_T); return CCONST_T;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "lexer.l"
{token_Print(LISTFUNC_T); return LISTFUNC_T;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 131 "lexer.l"
{token_Print(ID_T); return ID_T;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 133 "lexer.l"
{strcpy(str_Arr, ""); BEGIN(SBLXR_STRING);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 134 "lexer.l"
{BEGIN(INITIAL); printf("String Found: %s --> Token value: %d --> Program line: %d\n", str_Arr, STRING_T, yylineno); return STRING_T;}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 135 "lexer.l"
{ /*New line*/}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 136 "lexer.l"
{sp_chr_Handler(str_Arr);}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 137 "lexer.l"
{printf("Fake new line, invalid input");}
	YY_BREAK
case YY_STATE_EOF(SBLXR_STRING):
#line 138 "lexer.l"
{error_Handler(STRING_T, 0);/*printf("Reached EOF without closing string");*/}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 139 "lexer.l"
{error_Handler(STRING_T, -1);/*printf("Unknown char for sting");*/}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 141 "lexer.l"
{BEGIN(SBLXR_COMMENT);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 142 "lexer.l"
{BEGIN(INITIAL); printf("Comment found --> Token value: %d --> Program line %d\n", COMMENT_T, yylineno);}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 143 "lexer.l"
{ /*New line*/}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 144 "lexer.l"
{}
	YY_BREAK
case YY_STATE_EOF(SBLXR_COMMENT):
#line 145 "lexer.l"
{error_Handler(COMMENT_T, 0);/*printf("Reached EOF without closing comment");*/}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 146 "lexer.l"
{error_Handler(COMMENT_T, -1);/*printf("Unknown char for comment");*/}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 148 "lexer.l"
{token_Print(LPAREN_T); return LPAREN_T;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 149 "lexer.l"
{token_Print(RPAREN_T); return RPAREN_T;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 150 "lexer.l"
{token_Print(SEMI_T); return SEMI_T;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 151 "lexer.l"
{token_Print(DOT_T); return DOT_T;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 152 "lexer.l"
{token_Print(COMMA_T); return COMMA_T;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 153 "lexer.l"
{token_Print(EQU_T); return EQU_T;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 154 "lexer.l"
{token_Print(COLON_T); return COLON_T;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 155 "lexer.l"
{token_Print(LBRACK_T); return LBRACK_T;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 156 "lexer.l"
{token_Print(RBRACK_T); return RBRACK_T;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 157 "lexer.l"
{token_Print(ASSIGN_T); return ASSIGN_T;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 158 "lexer.l"
{token_Print(DOTDOT_T); return DOTDOT_T;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 160 "lexer.l"
{ }
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 161 "lexer.l"
{ }
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 162 "lexer.l"
{ }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 164 "lexer.l"
{ token_Print(EOF_T); return EOF_T; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 165 "lexer.l"
{error_Handler(ERROR_T, -1); /*printf("Unknown token found\n");*/}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 166 "lexer.l"
ECHO;
	YY_BREAK
#line 1468 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 240 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 240 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 239);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 166 "lexer.l"


/* FUNCTIONS */
// Main
int main(int argc, char* argv[]){
    
    if (argc > 1){
        yyin = fopen(argv[1], "r");

        if (yyin == NULL){
            perror("Can't open file!\n");
            return -1;
        }
    }
    
    int token;

    do{

        token = yylex();

    }while(token != 0);

    fclose(yyin);
    yyterminate();
        
    return 0;
}

/* Helpful Functions */
/* Printing all tokens */
void token_Print(int token_val){

    /* Printing arithmetic integer constants */
    if(token_val == ICONST_T){
        if(strncmp(yytext, "0B", 2) == 0){
            /* Printing binary integer constants */
            printf("Integer number(Binary) found: %s --> Decimal value: %d --> Token value: %d --> Program line: %d\n", yytext, str_int(yytext), token_val, yylineno);

        }else if(strncmp(yytext, "0X", 2) == 0){
            /* Printing hexadecimal integer constants */
            printf("Integer number(Hexadecimal) found: %s --> Decimal value: %d --> Token value: %d --> Program line: %d\n", yytext, str_int(yytext), token_val, yylineno);

        }else{
            /* Printing decimal integer constants */
            printf("Integer number(Decimal) found: %d --> Token value: %d --> Program line: %d\n", str_int(yytext), token_val, yylineno);
        }
    }else if(token_val == RCONST_T){
        if(strncmp(yytext, "0B", 2) == 0){
            /* Printing binary real constants */
            printf("Real number(Binary) found %s --> Decimal value: %f --> Token value: %d --> Program line: %d\n", yytext, str_float(yytext), token_val, yylineno);
        }else if(strncmp(yytext, "0X", 2) == 0){
            /* Printing hexadecimal real constants */
            printf("Real number(Hexadecimal) found %s --> Decimal value: %f --> Token value: %d --> Program line: %d\n", yytext, str_float(yytext), token_val, yylineno);
        }else{
            /* Printing decimal real constants */
            printf("Real number(Decimal) found %s --> Decimal value: %f --> Token value: %d --> Program line: %d\n", yytext, str_float(yytext), token_val, yylineno);
        }
    }else if(token_val == EOF_T){
        printf("EOF Reached --> Token value: %d --> Program line: %d\n", token_val, yylineno);
        printf("File Closed\n");
    }else{
        /* Printing the rest of the tokens */
        printf("Token found: %s --> Token value: %d --> Program line: %d\n", yytext, token_val, yylineno);
    }
}

/* Returning values of all arithmetic (Integer, Real) constants. */
/* Integer Constants */
int str_int(char *strptr){

    if(strncmp(strptr, "0B", 2) == 0){
        return (int)strtol(&strptr[2], NULL, 2);

    }else if(strncmp(strptr, "0X", 2) == 0){
        return (int)strtol(&strptr[2], NULL, 16);

    }else{
        return atoi(strptr);
    }
}


/* Real Constants */
float str_float(char *strptr){

    float f_num;
    if(strncmp(strptr, "0B", 2) == 0){

        char *after_dot = strchr(strptr, '.');
        f_num = (int)strtol(&strptr[2], &after_dot, 2);
        int i;
        for(i=1; i<=strlen(after_dot)-1; i++){
            f_num += (after_dot[i] - '0') * (1/pow(2,i));
        }

    }else if(strncmp(strptr, "0X", 2) == 0){

        char *after_dot = strchr(strptr, '.');
        f_num = (int)strtol(&strptr[2], &after_dot, 16);
        int i;
        for(i=1; i<=strlen(after_dot)-1; i++){
            if(after_dot[i] <= '9'){
                f_num += (after_dot[i] - '0') * (1/pow(16,i));
            }else{
                f_num += (after_dot[i] + 10 - 'A') * (1/pow(16,i));
            }
        }

    }else{

        int i, expo_check;
        for(i=0;i<=strlen(strptr)-1; i++){
            if(strptr[i] == 'E')
                expo_check = 1;
            if(strptr[i] == 'e')
                expo_check = 2;
        }
        
        if(expo_check == 1 || expo_check == 2){

            char *after_E;
            if(expo_check == 1){
                after_E = strchr(strptr, 'E');
            }else{
                after_E = strchr(strptr, 'e');
            }

            f_num = (float)strtol(strptr, &after_E, 10); //This Works(Kinda)!
            /*char *before_E;
            for(i=0; i<=strlen(strptr)-1-strlen(after_E); i++){
                before_E[i] = strptr[i];
            }
            f_num = atof(before_E);*/

            double expo_num;

            if(after_E[1] == '-'){

                int i;
                for(i=2; i<=strlen(after_E)-1; i++){
                    expo_num += after_E[i] - '0';
                }
                f_num = 1/pow(f_num, expo_num);
                
            }else{

                int i;
                for(i=1; i<=strlen(after_E)-1; i++){
                    expo_num += after_E[i] - '0';
                }
                f_num = pow(f_num, expo_num);
            }
        }else{
            f_num = atof(strptr);
        }
    }
    return f_num;
}

void sp_chr_Handler(char *str_Arr){

    if(strlen(yytext) == 2){
        if(strcmp(yytext, "\\n") == 0){
            strcat(str_Arr, "\n");
        }else if(strcmp(yytext, "\\f") == 0){
            strcat(str_Arr, "\f");
        }else if(strcmp(yytext, "\\t") == 0){
            strcat(str_Arr, "\t");
        }else if(strcmp(yytext, "\\r") == 0){
            strcat(str_Arr, "\r");
        }else if(strcmp(yytext, "\\b") == 0){
            strcat(str_Arr, "\b");
        }else if(strcmp(yytext, "\\v") == 0){
            strcat(str_Arr, "\v");
        }else{
            strcat(str_Arr, &yytext[1]);
        }
    }else{
        strcat(str_Arr, yytext);
    }
}

void error_Handler(int token_val, int id){

    if(token_val == STRING_T){
        if(id == 0){
            printf("EOF Reached, expected \" to close strings --> Program line: %d\n",yylineno);
            exit(-1);
        }else{
            printf("Unknown token found inside string --> Program line: %d\n", yylineno);
            yyless(1);
        }
    }else if(token_val == COMMENT_T){
        if(id == 0){
            printf("EOF Reached, expected } to close comments --> Program line: %d\n",yylineno);
            exit(-1);
        }else{
            printf("Unknown token found inside comment --> Program line: %d\n", yylineno);
            yyless(1);
        }
    }else{
        printf("Unknown token found --> Program line: %d\n", yylineno);
        yyless(1);
    }
}
